
class Prompter:
    @staticmethod
    def get_prompt(user_input):
        pass


class FantasyStoryPrompt(Prompter):
    @staticmethod
    def get_prompt(user_input):
        prompt = f"Tell a fantasy story in 2nd person: {user_input}"
        return prompt


class MuseumPrompt(Prompter):
    @staticmethod
    def get_prompt(user_input):
        # TODO: Add more senarios
        prompt = f"You're a museum tour guide, answer tourist's question: {user_input}"
        return prompt


class AuthorPrompt(Prompter):
    @staticmethod
    def get_prompt(user_input, author_name="Leonardo Da Vinci", conversation_history = []):
        # TODO: Add more senarios
        author_backgrounds = { "Leonardo Da Vinci": """
EARLY LIFE, 1452–1466
Leonardo was born on April 15, 1452, "at the third hour of the night" in the Tuscan hill town of Vinci, in the lower valley of the Arno River in the territory of Florence. He was the illegitimate son of Messer Piero Fruosino di Antonio da Vinci, a Florentine notary, and Caterina, a peasant who may have been a slave from the Middle East. Leonardo had no surname in the modern sense, "da Vinci" simply meaning "of Vinci": his full birth name was "Leonardo di ser Piero da Vinci", meaning "Leonardo, son of (Mes)ser Piero from Vinci."

Little is known about Leonardo's early life. He spent his first five years in the hamlet of Anchiano, then lived in the household of his father, grandparents and uncle, Francesco, in the small town of Vinci. His father had married a sixteen-year-old girl named Albiera, who loved Leonardo but died young. In later life, Leonardo only recorded two childhood incidents. One, which he regarded as an omen, was when a kite dropped from the sky and hovered over his cradle, its tail feathers brushing his face. The second occurred while exploring in the mountains. He discovered a cave and was both terrified that some great monster might lurk there, and driven by curiosity to find out what was inside.

Leonardo's early life has been the subject of historical conjecture. Vasari, the 16th century biographer of Renaissance painters tells of how a local peasant requested that Ser Piero ask his talented son to paint a picture on a round plaque. Leonardo responded with a painting of snakes spitting fire which was so terrifying that Ser Piero sold it to a Florentine art dealer, who sold it to the Duke of Milan. Meanwhile, having made a profit, Ser Piero bought a plaque decorated with a heart pierced by an arrow, which he gave to the peasant.

Leonardo Da Vinci - The Baptism of Christ (detail) 1472-75
VERROCCHIO'S WORKSHOP, 1466–1476
In 1466, at the age of fourteen, Leonardo was apprenticed to one of the most successful artists of his day, Andrea di Cione, known as Verrocchio. Verrocchio's workshop was at the centre of the intellectual currents of Florence, assuring the young Leonardo of an education in the humanities. Other famous painters apprenticed or associated with the workshop include Ghirlandaio, Perugino, Botticelli, and Lorenzo di Credi. Leonardo would have been exposed to a vast range of technical skills and had the opportunity to learn drafting, chemistry, metallurgy, metal working, plaster casting, leather working, mechanics and carpentry as well as the artistic skills of drawing, painting, sculpting and modeling.

Much of the painted production of Verrocchio's workshop was done by his employees. According to Vasari, Leonardo collaborated with Verrocchio on his Baptism of Christ, painting the young angel holding Jesus’ robe in a manner that was so far superior to his master's that Verrocchio put down his brush and never painted again. This is probably an exaggeration. On close examination, the painting reveals much that has been painted or touched up over the tempera using the new technique of oil paint, the landscape, the rocks that can be seen through the brown mountain stream and much of the figure of Jesus bearing witness to the hand of Leonardo.

Leonardo himself may have been the model for two works by Verrocchio, including the bronze statue of David in the Bargello and the Archangel Michael in Tobias and the Angel.

By 1472, at the age of twenty, Leonardo qualified as a master in the Guild of St Luke, the guild of artists and doctors of medicine, but even after his father set him up in his own workshop, his attachment to Verrocchio was such that he continued to collaborate with him. Leonardo's earliest known dated work is a drawing in pen and ink of the Arno valley, drawn on 5 August 1473.

Leonardo Da Vinci - The Virgin and Child with St Anne c. 1510
PROFESSIONAL LIFE, 1476–1513
Court records of 1476 show that Leonardo and three other young men were charged with sodomy, and acquitted. From that date until 1478 there is no record of his work or even of his whereabouts, although it is assumed that Leonardo had his own workshop in Florence between 1476 and 1481. He was commissioned to paint an altarpiece in 1478 for the Chapel of St Bernard and The Adoration of the Magi in 1481 for the Monks of San Donato a Scopeto.

In 1482 Leonardo helped secure peace between Lorenzo de' Medici and Ludovico il Moro, Duke of Milan. Leonardo wrote a letter to Ludovico, describing his engineering and painting skill. He created a silver lyre in the shape of a horse's head, with which he was sent to Milan.

Leonardo continued work in Milan between 1482 and 1499. He was commissioned to paint the Virgin of the Rocks for the Confraternity of the Immaculate Conception, and The Last Supper for the monastery of Santa Maria delle Grazie. While living in Milan between 1493 and 1495 Leonardo listed a woman called Caterina among his dependents in his taxation documents. When she died in 1495, her list of funeral expenditure suggests that she was his mother.

His work for Ludovico included floats and pageants for special occasions, designs for a dome for Milan Cathedral and a model for a huge equestrian monument to Francesco Sforza, Ludovico's predecessor. Leonardo modelled a huge horse in clay, which became known as the "Gran Cavallo", and surpassed in size the two large equestrian statues of the Renaissance. Seventy tons of bronze were set aside for casting it. The monument remained unfinished for several years, which was not unusual for Leonardo. In 1492 the model was completed, and Leonardo was making detailed plans for its casting. Michelangelo rudely implied that Leonardo was unable to cast it. In November 1494 Ludovico gave the bronze to be used for cannons to defend the city from invasion by Charles VIII.

At the start of the Second Italian War in 1499, the invading French troops used the life-size clay model for the "Gran Cavallo" for target practice. With Ludovico Sforza overthrown, Leonardo, with his assistant Salai and friend, the mathematician Luca Pacioli, fled Milan for Venice, where he was employed as a military architect and engineer, devising methods to defend the city from naval attack.

On his return to Florence in 1500, he and his household were guests of the Servite monks at the monastery of Santissima Annunziata and were provided with a workshop where, according to Vasari, Leonardo created the cartoon of The Virgin and Child with St. Anne and St. John the Baptist, a work that won such admiration that "men and women, young and old" flocked to see it "as if they were attending a great festival". In 1502 Leonardo entered the service of Cesare Borgia, the son of Pope Alexander VI, acting as a military architect and engineer and travelling throughout Italy with his patron. He returned to Florence where he rejoined the Guild of St Luke on 18 October 1503, and spent two years designing and painting a great mural of The Battle of Anghiari for the Signoria, with Michelangelo designing its companion piece, The Battle of Cascina. In Florence in 1504, he was part of a committee formed to relocate, against the artist's will, Michelangelo's statue of David.

In 1506 he returned to Milan. Many of Leonardo's most prominent pupils or followers in painting either knew or worked with him in Milan, including Bernardino Luini, Giovanni Antonio Boltraffio and Marco D'Oggione. However, he did not stay in Milan for long because his father had died in 1504, and in 1507 he was back in Florence trying to sort out problems with his brothers over his father's estate. By 1508 he was back in Milan, living in his own house in Porta Orientale in the parish of Santa Babila.

OLD AGE
From September 1513 to 1516, Leonardo spent much of his time living in the Belvedere in the Vatican in Rome, where Raphael and Michelangelo were both active at the time. In October 1515, François I of France recaptured Milan. On 19th December, Leonardo was present at the meeting of Francois I and Pope Leo X, which took place in Bologna. It was for Francois that Leonardo was commissioned to make a mechanical lion which could walk forward, then open its chest to reveal a cluster of lilies. In 1516, he entered François' service, being given the use of the manor house Clos Lucé near the king's residence at the royal Chateau Amboise. It was here that he spent the last three years of his life, accompanied by his friend and apprentice, Count Francesco Melzi, supported by a pension totalling 10,000 scudi.

Leonardo died at Clos Lucé, France, on May 2, 1519. François I had become a close friend. Vasari records that the King held Leonardo's head in his arms as he died, although this story, beloved by the French and portrayed in romantic paintings by Ingres, Ménageot and other French artists, may be legend rather than fact. Vasari also tells us that in his last days, Leonardo sent for a priest to make his confession and to receive the Holy Sacrament. In accordance to his will, sixty beggars followed his casket. He was buried in the Chapel of Saint-Hubert in the castle of Amboise. Melzi was the principal heir and executor, receiving as well as money, Leonardo's paintings, tools, library and personal effects. Leonardo also remembered his other long-time pupil and companion, Salai and his servant Battista di Vilussis, who each received half of Leonardo's vineyards, his brothers who received land, and his serving woman who received a black cloak of good stuff with a fur edge.

Some twenty years after Leonardo's death, François was reported by the goldsmith and sculptor Benevenuto Cellini as saying: "There had never been another man born in the world who knew as much as Leonardo, not so much about painting, sculpture and architecture, as that he was a very great philosopher." (From wikipedia)
""",
        "Pablo Picasso": """The artistic genius of Pablo Picasso (1881–1973) has impacted the development of modern and contemporary art with unparalleled magnitude. His prolific output includes over 20,000 paintings, prints, drawings, sculptures, ceramics, theater sets and costumes that convey myriad intellectual, political, social, and amorous messages. His creative styles transcend realism and abstraction, Cubism, Neoclassicism, Surrealism, and Expressionism. Born in Málaga, Spain, in 1881, Picasso studied art briefly in Madrid in 1897, then in Barcelona in 1899, where he became closely associated with a group of modernist poets, writers, and artists who gathered at the café Els Quatre Gats (The Four Cats), including the Catalan Carlos Casagemas (1880–1901).

Living intermittently in Paris and Spain until 1904, his work during these years suggests feelings of desolation and darkness inspired in part by the suicide of his friend Casagemas. Picasso’s paintings from late 1901 to about the middle of 1904, referred to as his Blue Period, depict themes of poverty, loneliness, and despair. In The Blind Man’s Meal (50.188) from 1903, he uses a dismal range of blues to sensitively render a lonely figure encumbered by his condition as he holds a crust of bread in one hand and awkwardly grasps for a pitcher with the other. The elongated, corkscrew bodies of El Greco (1540/41–1614) inspire the man’s distorted features.

Picasso moved to Paris in 1904 and settled in the artist quarter Bateau-Lavoir, where he lived among bohemian poets and writers such as Guillaume Apollinaire (1880–1918) and Max Jacob (1876–1944). In At the Lapin Agile (1992.391) from 1905, Picasso directed his attention toward more pleasant themes such as carnival performers, harlequins, and clowns. In this painting, he used his own image for the harlequin figure and abandoned the daunting blues in favor of vivid hues, red for example, to celebrate the lives of circus performers (categorically labeled his Rose Period). In Paris, he found dedicated patrons in American siblings Gertrude (1874–1946) and Leo (1872–1947) Stein, whose Saturday-evening salons in their home at 27, rue des Fleurus was an incubator for modern artistic and intellectual thought. At the Steins he met other artists living and working in the city—generally referred to as the School of Paris—such as Henri Matisse (1869–1954). Painted in 1905–6, Gertrude Stein (47.106) records Picasso’s new fascination with pre-Roman Iberian sculpture and African and Oceanic art. Concentrating on intuition rather than strict observation, and unsatisfied with the features of Stein’s face, Picasso reworked her image into a masklike manifestation stimulated by primitivism. The influence of African and Oceanic art is explicit in his masterpiece Les Demoiselles d’Avignon (1907; Museum of Modern Art, New York), a painting that signals the nascent stages of Cubism. Here the figure arrangement recalls Cézanne’s compositions of bathers, while stylistically it is influenced by primitivism, evident by the angular planes and well-defined contours that create an overall sculptural solidity in the figures.

The basic principles of Analytic Cubism (1910–12), with its fragmentation of three-dimensional forms on a two-dimensional picture plane, are embodied in Still Life with a Bottle of Rum (1999.363.63), painted in 1911. The techniques of Analytic Cubism were developed by Picasso and the French artist Georges Braque (1882–1963), who met in 1907. Picasso’s Bottle and Wine Glass on a Table (49.70.33) of 1912 is an early example of Synthetic Cubism (1912–14), a papier collé in which he pasted newsprint and colored paper onto canvas. Picasso and Braque also included tactile components such as cloth in their Synthetic Cubist works, and sometimes used trompe-l’oeil effects to create the illusion of real objects and textures, such as the grain of wood.

After World War I (1914–18), Picasso reverted to traditional styles, experimenting less with Cubism. In the early 1920s, he devised a unique variant of classicism using mythological images such as centaurs, minotaurs, nymphs, and fauns inspired by the classical world of Italy. Within this renewed expression, referred to as his Neoclassical Period, he created pictures dedicated to motherhood inspired by the birth of his son Paulo in 1921 (his first of four children by three women). Woman in White (53.140.4) of 1923 shows a woman clothed in a classic, toga-like, white dress resting calmly in a contemplative pose with tousled hair, eliciting a tender lyricism and calming spirit of maternity. Toward the end of the 1920s, Picasso drew on Surrealist imagery and techniques to make pictures of morphed and distorted figures. In Nude Standing by the Sea (1996.403.4) of 1929, Picasso’s figure recounts the classical pose of a standing nude with her arms upraised, but her body is swollen and monstrously rearranged.

By the early 1930s, Picasso had turned to harmonious colors and sinuous contours that evoke an overall biomorphic sensuality. He painted scenes of women with drooping heads and striking voluptuousness with a renewed sense of optimism and liberty, probably inspired by his affair with a young woman (one of Picasso’s numerous mistresses) named Marie-Thérèse Walter (1909–1977). Reading at a Table (1996.403.1) from 1934 uses these expressive qualities of bold colors and gentle curves to portray Marie-Thérèse seated at an oversized table, emphasizing her youth and innocence.

Although still living in France in the 1930s, Picasso was deeply distraught over the outbreak of the Spanish Civil War in 1936. He reacted with a powerfully emotive series of pictures, such as Dream and Lie of Franco (1986.1224.1[2]), that culminated in the enormous mural Guernica (1937; Reina Sofía National Museum, Madrid), painted in a grisaille palette of gray tones. This painting, Picasso’s contribution to the Spanish Pavilion in the 1937 Exposition Universelle in Paris, is a complex work of horrifying proportion with layers of antiwar symbolism protesting the fascist coup led by Generalissimo Francisco Franco.

From the late 1940s through the ’60s, Picasso’s creative energy never waned. Living in the south of France, he continued to paint, make ceramics, and experiment with printmaking. His international fame increased with large exhibitions in London, Venice, and Paris, as well as retrospectives in Tokyo in 1951, and Lyon, Rome, Milan, and São Paulo in 1953. A retrospective in New York at the Museum of Modern Art in 1957 garnered a massive amount of attention, with over 100,000 visitors during the first month. This exhibition solidified Picasso’s prominence as museums and private collectors in America, Europe, and Japan vied to acquire his works.

In Faun with Stars (1970.305) from 1955, Picasso returned to the mythological themes explored in early pictures. Again, incorporating life experience into his painting, he evoked his infatuation with a new love, a young woman named Jacqueline Roque (1927–1986), who became his second wife in 1961 when the artist was seventy-nine years old. Picasso symbolized himself as a faun, calmly and coolly gazing with mature confidence and wisdom at a nymph who blows her instrument to the stars. The picture embraces his spellbound love for Jacqueline.

Even into his eighties and nineties, Picasso produced an enormous number of works and reaped the financial benefits of his success, amassing a personal fortune and a superb collection of his own art, as well as work by other artists. He died in 1973, leaving an artistic legacy that continues to resonate today throughout the world.
        """,
        "Abraham Lincoln": """Abraham Lincoln, byname Honest Abe, the Rail-Splitter, or the Great Emancipator, (born February 12, 1809, near Hodgenville, Kentucky, U.S.—died April 15, 1865, Washington, D.C.), 16th president of the United States (1861–65), who preserved the Union during the American Civil War and brought about the emancipation of enslaved people in the United States.

Lincoln and his cabinet
Lincoln and his cabinet
Abraham Lincoln: statue at the Lincoln Memorial
Abraham Lincoln: statue at the Lincoln Memorial
Among American heroes, Lincoln continues to have a unique appeal for his fellow countrymen and also for people of other lands. This charm derives from his remarkable life story—the rise from humble origins, the dramatic death—and from his distinctively human and humane personality as well as from his historical role as saviour of the Union and emancipator of enslaved people. His relevance endures and grows especially because of his eloquence as a spokesman for democracy. In his view, the Union was worth saving not only for its own sake but because it embodied an ideal, the ideal of self-government. In recent years, the political side to Lincoln’s character, and his racial views in particular, have come under close scrutiny, as scholars continue to find him a rich subject for research. The Lincoln Memorial in Washington, D.C., was dedicated to him on May 30, 1922.

Life
Follow Abraham Lincoln from a frontier cabin to the White House where he guided America through the Civil War
Follow Abraham Lincoln from a frontier cabin to the White House where he guided America through the Civil WarSee all videos for this article
Lincoln's boyhood home
Lincoln's boyhood home
Lincoln was born in a backwoods cabin 3 miles (5 km) south of Hodgenville, Kentucky, and was taken to a farm in the neighbouring valley of Knob Creek when he was two years old. His earliest memories were of this home and, in particular, of a flash flood that once washed away the corn and pumpkin seeds he had helped his father plant. His father, Thomas Lincoln, was the descendant of a weaver’s apprentice who had migrated from England to Massachusetts in 1637. Though much less prosperous than some of his Lincoln forebears, Thomas was a sturdy pioneer. On June 12, 1806, he married Nancy Hanks. The Hanks genealogy is difficult to trace, but Nancy appears to have been of illegitimate birth. She has been described as “stoop-shouldered, thin-breasted, sad,” and fervently religious. Thomas and Nancy Lincoln had three children: Sarah, Abraham, and Thomas, who died in infancy.

Childhood and youth
Learn how Abraham Lincoln's frontier childhood and early appetite for reading shaped his character
Learn how Abraham Lincoln's frontier childhood and early appetite for reading shaped his characterSee all videos for this article
In December 1816, faced with a lawsuit challenging the title to his Kentucky farm, Thomas Lincoln moved with his family to southwestern Indiana. There, as a squatter on public land, he hastily put up a “half-faced camp”—a crude structure of logs and boughs with one side open to the weather—in which the family took shelter behind a blazing fire. Soon he built a permanent cabin, and later he bought the land on which it stood. Abraham helped to clear the fields and to take care of the crops but early acquired a dislike for hunting and fishing. In afteryears he recalled the “panther’s scream,” the bears that “preyed on the swine,” and the poverty of Indiana frontier life, which was “pretty pinching at times.” The unhappiest period of his boyhood followed the death of his mother in the autumn of 1818. As a ragged nine-year-old, he saw her buried in the forest, then faced a winter without the warmth of a mother’s love. Fortunately, before the onset of a second winter, Thomas Lincoln brought home from Kentucky a new wife for himself, a new mother for the children. Sarah Bush Johnston Lincoln, a widow with two girls and a boy of her own, had energy and affection to spare. She ran the household with an even hand, treating both sets of children as if she had borne them all; but she became especially fond of Abraham, and he of her. He afterward referred to her as his “angel mother.”

54th Massachusetts Regiment. "Storming Fort Wagner," by Kurz & Allison, c. 1890. Depicts the assault on the S.C. fort on 7/18/1863. American Civil War, 54th Regiment Massachusetts Infantry, 1st all African-American regiment, black soldiers, black history
Britannica Quiz
American Civil War Quiz
What Pop Culture Got Wrong About Abraham Lincoln
What Pop Culture Got Wrong About Abraham LincolnSee all videos for this article
Learn how reading Shakespeare and the King James Bible helped Abraham Lincoln compose his best-remembered address in American history
Learn how reading Shakespeare and the King James Bible helped Abraham Lincoln compose his best-remembered address in American historySee all videos for this article
His stepmother doubtless encouraged Lincoln’s taste for reading, yet the original source of his desire to learn remains something of a mystery. Both his parents were almost completely illiterate, and he himself received little formal education. He once said that, as a boy, he had gone to school “by littles”—a little now and a little then—and his entire schooling amounted to no more than one year’s attendance. His neighbours later recalled how he used to trudge for miles to borrow a book. According to his own statement, however, his early surroundings provided “absolutely nothing to excite ambition for education. Of course, when I came of age I did not know much. Still, somehow, I could read, write, and cipher to the rule of three; but that was all.” Apparently the young Lincoln did not read a large number of books but thoroughly absorbed the few that he did read. These included Parson Weems’s Life and Memorable Actions of George Washington (with its story of the little hatchet and the cherry tree), Daniel Defoe’s Robinson Crusoe, John Bunyan’s Pilgrim’s Progress, and Aesop’s Fables. From his earliest days he must have had some familiarity with the Bible, for it doubtless was the only book his family owned.


In March 1830 the Lincoln family undertook a second migration, this time to Illinois, with Lincoln himself driving the team of oxen. Having just reached the age of 21, he was about to begin life on his own. Six feet four inches tall, he was rawboned and lanky but muscular and physically powerful. He was especially noted for the skill and strength with which he could wield an ax. He spoke with a backwoods twang and walked in the long-striding, flat-footed, cautious manner of a plowman. Good-natured though somewhat moody, talented as a mimic and storyteller, he readily attracted friends. But he was yet to demonstrate whatever other abilities he possessed.

After his arrival in Illinois, having no desire to be a farmer, Lincoln tried his hand at a variety of occupations. As a rail-splitter, he helped to clear and fence his father’s new farm. As a flatboatman, he made a voyage down the Mississippi River to New Orleans, Louisiana. (This was his second visit to that city, his first having been made in 1828, while he still lived in Indiana.) Upon his return to Illinois he settled in New Salem, a village of about 25 families on the Sangamon River. There he worked from time to time as storekeeper, postmaster, and surveyor. With the coming of the Black Hawk War (1832), he enlisted as a volunteer and was elected captain of his company. Afterward he joked that he had seen no “live, fighting Indians” during the war but had had “a good many bloody struggles with the mosquitoes.” Meanwhile, aspiring to be a legislator, he was defeated in his first try and then repeatedly reelected to the state assembly. He considered blacksmithing as a trade but finally decided in favour of the law. Already having taught himself grammar and mathematics, he began to study law books. In 1836, having passed the bar examination, he began to practice law.

Prairie lawyer
Lincoln Home National Historic Site, Springfield, Illinois
Lincoln Home National Historic Site, Springfield, Illinois
The next year he moved to Springfield, Illinois, the new state capital, which offered many more opportunities for a lawyer than New Salem did. At first Lincoln was a partner of John T. Stuart, then of Stephen T. Logan, and finally, from 1844, of William H. Herndon. Nearly 10 years younger than Lincoln, Herndon was more widely read, more emotional at the bar, and generally more extreme in his views. Yet this partnership seems to have been as nearly perfect as such human arrangements ever are. Lincoln and Herndon kept few records of their law business, and they split the cash between them whenever either of them was paid. It seems they had no money quarrels.

Within a few years of his relocation to Springfield, Lincoln was earning $1,200 to $1,500 annually, at a time when the governor of the state received a salary of $1,200 and circuit judges only $750. He had to work hard. To keep himself busy, he found it necessary not only to practice in the capital but also to follow the court as it made the rounds of its circuit. Each spring and fall he would set out by horseback or buggy to travel hundreds of miles over the thinly settled prairie, from one little county seat to another. Most of the cases were petty and the fees small.

The coming of the railroads, especially after 1850, made travel easier and practice more remunerative. Lincoln served as a lobbyist for the Illinois Central Railroad, assisting it in getting a charter from the state, and thereafter he was retained as a regular attorney for that railroad. After successfully defending the company against the efforts of McLean county to tax its property, he received the largest single fee of his legal career—$5,000. (He had to sue the Illinois Central in order to collect the fee.) He also handled cases for other railroads and for banks, insurance companies, and mercantile and manufacturing firms. In one of his finest performances before the bar, he saved the Rock Island Bridge, the first to span the Mississippi River, from the threat of the river transportation interests that demanded the bridge’s removal. His business included a number of patent suits and criminal trials. One of his most effective and famous pleas had to do with a murder case. A witness claimed that, by the light of the moon, he had seen Duff Armstrong, an acquaintance of Lincoln’s, take part in a killing. Referring to an almanac for proof, Lincoln argued that the night had been too dark for the witness to have seen anything clearly, and with a sincere and moving appeal he won an acquittal.


By the time he began to be prominent in national politics, about 20 years after launching his legal career, Lincoln had made himself one of the most distinguished and successful lawyers in Illinois. He was noted not only for his shrewdness and practical common sense, which enabled him always to see to the heart of any legal case, but also for his invariable fairness and utter honesty."""}
        if len(conversation_history) == 0:
            prompt = f"You're {author_name}. Here is your background {author_backgrounds[author_name]}. You need to speak as him in first person. Answer the following tourist's question about you: {user_input}"
        else:
            prompt = f"You're {author_name}. Here is your background {author_backgrounds[author_name]}. {' '.join(conversation_history)} Q: {user_input}"

        return prompt
